app = "35a52cf8-ids"
primary_region = "jnb"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile.ids.identity.hstai"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  
  # Database connection string
  ConnectionStrings__DefaultConnection = "Data Source=62.171.156.247;Initial Catalog=35a52cf8ids;User ID=sa;Password=123@Teams"
  
  # Service URLs
  IdentitySettings__Authority = "https://35a52cf8-ids.fly.dev/"
  IdentitySettings__TokenEndpoint = "https://35a52cf8-ids.fly.dev/connect/token"
  IdentitySettings__UserInformationEndpoint = "https://35a52cf8-ids.fly.dev/connect/userinfo"
  IdentitySettings__AuthorizationEndpoint = "https://35a52cf8-ids.fly.dev/connect/authorize"
  IdentitySettings__SelfUrl = "https://35a52cf8-ids.fly.dev/"
  IdentitySettings__MetadataAddress = "https://35a52cf8-ids.fly.dev/.well-known/openid-configuration"
  IdentitySettings__ApiUrl = "https://35a52cf8-host.fly.dev/"
  
  # Seed data environment variables
  SeedData__AllowedCorsOrigins__0 = "https://35a52cf8-web.fly.dev"
  SeedData__AllowedCorsOrigins__1 = "https://35a52cf8-host.fly.dev"
  SeedData__RedirectUris__0 = "https://35a52cf8-web.fly.dev/signin-oidc"
  SeedData__PostLogoutRedirectUris__0 = "https://35a52cf8-web.fly.dev/signout-callback-oidc"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"