app = "35a52cf8-kingsinns-web"
primary_region = "jnb"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile.web.ui.hstai"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  
  # Service URLs
  SelfUrl = "https://35a52cf8-kingsinns-web.fly.dev"
  IdentitySettings__Authority = "https://35a52cf8-kingsinns-ids.fly.dev"
  IdentitySettings__TokenEndpoint = "https://35a52cf8-kingsinns-ids.fly.dev/connect/token"
  IdentitySettings__UserInformationEndpoint = "https://35a52cf8-kingsinns-ids.fly.dev/connect/userinfo"
  IdentitySettings__AuthorizationEndpoint = "https://35a52cf8-kingsinns-ids.fly.dev/connect/authorize"
  IdentitySettings__MetadataAddress = "https://35a52cf8-kingsinns-ids.fly.dev/.well-known/openid-configuration"
  IdentitySettings__ApiUrl = "https://35a52cf8-kingsinns-host.fly.dev/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"